src/common/components/dropdown/styles.module.scss, src/common/components/input/styles.module.scss, src/pages/home-page/components/main-content/components/baner-block/styles.module.scss, src/pages/home-page/components/main-content/components/search-block/components/not-found/styles.module.scss, src/pages/home-page/components/main-content/components/search-block/index.tsx
=> changed styles

src/assets/images/minus.svg, src/assets/images/plus.svg, src/assets/styles/variables.scss, src/common/components/icon/icon-name-to-svg.ts, src/common/constants/mock-question-and-answers.ts, src/common/enums/icon-name.enum.ts, src/pages/home-page/components/main-content/components/index.ts, src/pages/home-page/components/main-content/components/question-and-answer-section/components/index.ts, src/pages/home-page/components/main-content/components/question-and-answer-section/components/question-and-answer-item/index.tsx, src/pages/home-page/components/main-content/components/question-and-answer-section/components/question-and-answer-item/styles.module.scss, src/pages/home-page/components/main-content/components/question-and-answer-section/index.tsx, src/pages/home-page/components/main-content/components/question-and-answer-section/styles.module.scss, src/pages/home-page/components/main-content/index.tsx
added faq section on home page
=> added faq section

src/common/components/button/index.tsx, src/common/components/button/styles.module.scss, src/common/enums/app-route.enum.ts, src/common/enums/button-variants.enum.ts, src/pages/home-page/components/main-content/components/companies-section/index.tsx, src/pages/home-page/components/main-content/components/items-header/index.tsx, src/pages/home-page/components/main-content/components/new-courses-section/index.tsx, src/pages/home-page/components/main-content/components/question-and-answer-section/index.tsx, src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
added  button functions to redirect in appropriate page( for top companies, top courses, new courses and faq sections)
added outlined button variants with arrow for mobile
=> Faq section

.env.exapmle, README.md, eslint.config.js, src/main.tsx
add lint rule
add env example
add readme file
=> Companies page

src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx
fix type for getCompanies in search element
=> fix companies type in search

src/common/components/breadcrumb/styles.module.scss, src/common/components/sort-dropdown/styles.module.scss, src/common/constants/other-footer-links.ts, src/common/enums/app-route.enum.ts, src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/components/company-category/styles.module.scss, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-table/styles.module.scss
changed link to faq page
changed styles for breadcrumbs
=> changed route and styles for breadcrumb

src/common/types/index.ts, src/common/types/review/get-moderation-reviews.ts, src/common/types/review/index.ts, src/pages/moderators-page/components/index.ts, src/pages/moderators-page/components/main-content/components/index.ts, src/pages/moderators-page/components/main-content/components/review-card/index.tsx, src/pages/moderators-page/components/main-content/index.tsx, src/pages/moderators-page/components/main-content/styles.module.scss, src/pages/moderators-page/componets/index.ts, src/pages/moderators-page/componets/main-moderators-content/index.tsx, src/pages/moderators-page/index.tsx, src/pages/moderators-page/styles.module.scss, src/redux/reviews-moderation/constans.ts, src/redux/reviews-moderation/reviews-moderation-api.ts, src/redux/reviews-moderation/reviews-moderation-slice.ts, src/redux/services.ts, src/redux/store.ts
- update redux;
- add components
=> add moderation-reviews

src/common/components/header/index.tsx, src/common/components/pagination/index.tsx, src/common/components/pagination/styles.module.scss, src/common/components/sort-dropdown/index.tsx, src/common/constants/mock-data/mock-user-reviews.ts, src/pages/companies-list-page/components/companies-list/components/filter-section/components/companies-categories/index.tsx, src/pages/companies-list-page/components/companies-list/components/filter-section/components/filter-section-text/index.tsx, src/pages/companies-list-page/components/companies-list/components/filter-section/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card-desktop/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/components/company-list-card/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/companies-list/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/components/company-card/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx, src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx, src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss, src/pages/companies-list-page/components/companies-list/components/reviews-section/index.tsx
=> translated all companies page

src/common/types/courses/get-courses-request-query.type.ts, src/pages/home-page/components/main-content/components/search-block/components/search-element/index.tsx, src/redux/courses/courses-api.ts, src/redux/courses/courses-slice.ts
added courses filters in state
changed logic for saving and removing filters on search bar on home page. change filters according to selected category
=> added filters for courses

.env.exapmle, src/redux/auth/auth-api.ts, src/redux/auth/constants.ts
added redirect_uri query in login request
=> added redirect link query

src/common/constants/companies-sort-options.ts
added sort option for companies
=> added sort option

src/common/components/search-bar/index.tsx, src/common/constants/courses-sort-options.ts, src/pages/course-list-page/components/course-list/components/filter-result-items/index.tsx, src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx, src/pages/course-list-page/components/course-list/components/filter-result-title/styles.module.scss, src/pages/course-list-page/components/course-list/components/filter-section/index.tsx, src/pages/course-list-page/components/course-list/index.tsx, src/pages/course-list-page/components/course-list/styles.module.scss
add sort on courses list page,
change styles
=> add sort for courses, change styles

src/common/types/index.ts, src/common/types/review/get-reviews-by-company-id-response-dto.type.ts, src/common/types/review/index.ts, src/pages/company-details-page/components/company-details/components/courses/components/course-card/course-card.tsx, src/pages/company-details-page/components/company-details/components/courses/courses.tsx, src/pages/home-page/components/main-content/components/course-card/index.tsx, src/pages/home-page/components/main-content/components/new-courses-section/index.tsx, src/pages/home-page/components/main-content/components/top-courses-section/index.tsx, src/pages/home-page/components/main-content/index.tsx, src/redux/companies/companies-api.ts, src/redux/courses/courses-api.ts
change types for courses and companies
=> Code refactor

src/common/components/course-card/index.tsx, src/common/components/footer/index.tsx, src/common/components/icon/icon-name-to-svg.ts, src/common/components/logo/styles.module.scss, src/common/components/pagination/index.tsx, src/common/constants/index.ts, src/common/constants/other-footer-links.ts, src/common/enums/icon-name.enum.ts, src/common/types/get-query-response.type.ts, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/index.tsx, src/pages/companies-list-page/components/companies-list/components/filtered-companies-list/styles.module.scss, src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx, src/pages/course-list-page/components/course-list/index.tsx, src/pages/home-page/components/main-content/components/companies-section/components/company-card/styles.module.scss, src/pages/home-page/components/main-content/components/course-card/index.tsx, src/pages/home-page/components/main-content/components/course-card/styles.module.scss, src/pages/home-page/components/main-content/components/top-courses-section/index.tsx
=> add changes

src/common/components/sort-dropdown/index.tsx, src/pages/moderators-page/components/main-content/components/filter-section/index.tsx, src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss, src/pages/moderators-page/components/main-content/index.tsx
moved the state of sort filters from useState to useSearchParams to save their values between modals
=> useSearchParams in filters

src/common/types/user/user.type.ts, src/pages/privacy-policy/index.tsx, src/pages/privacy-policy/styles.module.scss, src/redux/auth/auth-slice.ts
added user property (policy_agreed) and condition for buttons on privacy policy page
=> added user property policy_agreed and condition on p&p page

src/common/components/breadcrumb/styles.module.scss, src/common/components/check-dropdown/components/subcategory-item/styles.module.scss, src/common/components/check-dropdown/styles.module.scss, src/common/components/modal/styles.module.scss, src/pages/course-list-page/components/course-list/components/filter-result-items/styles.module.scss, src/pages/course-list-page/components/course-list/components/filter-result-title/index.tsx, src/pages/course-list-page/components/course-list/components/filter-section/index.tsx, src/pages/course-list-page/components/course-list/index.tsx, src/pages/course-list-page/components/course-list/styles.module.scss, src/pages/course-list-page/styles.module.scss, src/redux/services.ts
=> fix bugs on courses list page

package-lock.json, package.json, src/redux/auth/auth-slice.ts, src/redux/services.ts
=> add mutex to auth

src/common/components/index.ts, src/common/components/protected-route/index.tsx, src/main.tsx
added protected rout to moderators page
=> feat: added protected rout to moderators page

src/pages/auth/index.tsx, src/pages/auth/styles.module.scss
=> fix bugs on auth page

src/common/components/breadcrumb/styles.module.scss, src/common/components/search-bar/index.tsx, src/common/components/search-input/styles.module.scss, src/common/components/sort-dropdown/index.tsx, src/common/components/sort-dropdown/styles.module.scss, src/common/components/toggle-group-buttons/styles.module.scss, src/pages/moderators-page/components/main-content/components/filter-section/index.tsx, src/pages/moderators-page/components/main-content/components/filter-section/styles.module.scss, src/pages/moderators-page/components/main-content/index.tsx, src/pages/moderators-page/components/main-content/styles.module.scss
fix styling bugs (or new designers changes)
added clearing filters in different situations
=> fix: fix bugs

src/common/types/review/get-course-reviews-dto.type.ts, src/pages/course-details-page/components/main-content/components/contacts-bar/index.tsx, src/pages/course-details-page/components/main-content/components/navigation-bar/styles.module.scss, src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx
=> Course details page

src/common/types/my-reviews/get-my-reviews-params.type.ts, src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/index.tsx, src/pages/companies-list-page/components/companies-list/components/reviews-section/components/review-card/styles.module.scss, src/pages/companies-list-page/components/companies-list/components/reviews-section/index.tsx, src/pages/company-details-page/components/company-details/components/reviews/components/statistics.tsx, src/pages/course-details-page/components/main-content/components/contacts-bar/styles.module.scss, src/pages/course-details-page/components/main-content/components/reviews-bar/components/review-modal/index.tsx, src/pages/course-details-page/components/main-content/components/reviews-bar/index.tsx, src/pages/course-details-page/components/main-content/styles.module.scss, src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/edit-review-modal/index.tsx, src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/edit-review-modal/styles.module.scss, src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/review-text-section/index.tsx, src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/components/review-text-section/styles.module.scss, src/pages/my-reviews-page/components/main-content/components/my-reviews-list-section/index.tsx, src/redux/reviews/reviews-companies-api.ts, src/redux/reviews/reviews-course-api.ts, src/redux/store.ts
added limit for leaving review by moderator
added courses and companies review api to store
correct styles
correct my review card with long world
changes in review section on companies list page
=> Course reviews

src/common/components/input/index.tsx, src/common/components/input/styles.module.scss, src/common/components/toggle-group-buttons/index.tsx, src/common/hooks/use-app-form.hook.ts, src/pages/faq-page/components/main-content/components/question-and-answer-section/index.tsx, src/pages/faq-page/components/main-content/components/question-and-answer-section/styles.module.scss, src/pages/faq-page/components/main-content/components/send-question/index.tsx, src/pages/faq-page/components/main-content/components/send-question/styles.module.scss
fix styling bugs, added form validation
=> fix: fix styling bugs, added form validation

src/redux/reviews/reviews-course-api.ts
=> fix type in get course reviews query

src/pages/company-details-page/components/company-details/components/reviews/components/components/share-modal.tsx, src/pages/course-details-page/components/main-content/components/reviews-bar/components/reviews-list/components/review/components/review-footer/components/share-modal/index.tsx
naming for X path in ENV is VITE_X_UPLOAD_URL
=> fixed path name for X shares
